#!/bin/sh
set -e

if [ "$#" -ne 1 -o -z "$1" ]; then
	echo usage: $0 ex >&2
	echo Creates a new exercise \'ex\' >&2
	exit 1
fi


mkdir "$1"
mkdir "$1/lib"
sed "s/french/$1/" french/dune >"$1/dune"
sed "s/french/$1/" french/lib/dune >"$1/lib/dune"
#taken from a comment below https://stackoverflow.com/a/12487497
c=`echo "$1" |sed 's/./\U&/'`
sed "s/French/$c/" french/c.ml >"$1/c.ml"
