#!/bin/sh
if [ -z "$1" ]; then
	echo usage: $0 user 2>&1
	exit 1
fi

if [ "$1" = "--user" -a -n "$2" ]; then
	git clone `pwd` ~/ex
	cd
	mv -f ex/* ex/.* .
	rmdir ex
	ln -s "$2" . #opam
	yes |opam init
else
	sudo -v && export SUDO=sudo || export SUDO="echo sudo"
	$SUDO adduser $1 ocaml
	$SUDO -u $1 `pwd`/$0 --user ~/.opam
fi
